name: microkit
networks:
  development:
    driver: bridge

volumes:
  microkit_postgres:

services:
  postgres:
    image: postgres
    container_name: microkit-postgres
    restart: always
    networks:
      - development
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=Developer01
    volumes:
      - microkit_postgres:/var/lib/postgresql/data

  rabbitmq:
    image: masstransit/rabbitmq
    container_name: microkit-rabbitmq
    restart: always
    networks:
      - development
    ports:
      - 15672:15672
      - 5672:5672
      - 5671:5671
      - 15671:15671
