name: microkit
networks:
  development:
    driver: bridge

volumes:
  microkit_postgres:

services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    networks:
      - development
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=Developer01
    volumes:
      - microkit_postgres:/var/lib/postgresql

  rabbitmq:
    image: masstransit/rabbitmq
    container_name: rabbitmq
    restart: always
    networks:
      - development
    ports:
      - 15672:15672 # UI
      - 5672:5672   # AMQP
      - 5671:5671   # AMQP TLS
      - 15671:15671 # Management TLS

  aspire-dashboard:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:latest
    container_name: aspire
    restart: always
    networks:
      - development
    ports:
      - "18888:18888" # UI
      - "4317:18889"  # OTLP gRPC
      - "4318:18890"  # OTLP HTTP
    environment:
      - DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS=true
