service_name: TestService
service_desc: A test service
host: localhost
log_level: info
port_offset: 9
database_url: postgres://postgres:Developer01@localhost
database_name: awesomeservice
database_drop: false
auth: null
otel: null
